extraction-2-init-reusable-transforms-and-setup-test-utils
pipedrive/CodeshiftCommunity pull request #12
Opened 2021-11-30 06:07 UTC by kiprasmel

2021-11-30 14:42 UTC, martikaljuve commented on tsconfig.json
> +      "@codeshift/*": ["../packages/*/src", "../packages/reusable-transforms"]
Probably unnecessary?

2021-11-30 14:46 UTC, martikaljuve commented on community/@pipedrive__convention-ui-react/src/test-utils/inlineTest.ts
> +export type InlinteTestRet = ReturnType<typeof defineInlineTest>;
```suggestion
export type InlineTestRet = ReturnType<typeof defineInlineTest>;
```

2021-11-30 14:50 UTC, martikaljuve commented on community/@pipedrive__convention-ui-react/src/test-utils/inlineTest.ts
> +             * though JS & TS already deep in what I wanna support.
update?

2021-11-30 14:52 UTC, martikaljuve approved these changes

2021-11-30 14:52 UTC, martikaljuve requested changes
.

2021-11-30 16:05 UTC, kiprasmel commented on CODEOWNERS
> +/packages/reusable-transforms/ @kiprasmel
fyi, this is because i want to be a codeowner on upstream.

2021-12-02 14:13 UTC, kiprasmel commented on tsconfig.json
> +      "@codeshift/*": ["../packages/*/src", "../packages/reusable-transforms"]
fixed

2021-12-02 14:26 UTC, kiprasmel commented on community/@pipedrive__convention-ui-react/src/test-utils/inlineTest.ts
> +             * though JS & TS already deep in what I wanna support.
updated.

2021-12-13 10:42 UTC, martikaljuve commented on packages/reusable-transforms/src/utils/Transformer.ts
> +	...transformerParamsExceptConfig: [j: JSCodeshift, src: Collection<any>, fileInfo: FileInfo, api: API, options: Options]
I think these named tuples are not supported by the old (1.x) version of Prettier that this project is using. Could we upgrade Prettier to 2.x (latest seems to be 2.5.1)?

2021-12-13 10:43 UTC, martikaljuve approved these changes

2021-12-23 00:11 UTC, merged