extraction-3-create-1st-transform-add-missing-jsx-attr-and-initial-codemod-setup
pipedrive/CodeshiftCommunity pull request #13
Opened 2021-11-30 06:10 UTC by kiprasmel

2021-11-30 14:55 UTC, martikaljuve commented on community/@pipedrive__convention-ui-react/src/5.0.0/config.ts
> +export const cuiLibraryName = "@pipedrive/convention-ui-react" as const; //  TODO EXTRACT. atm only used in specific configs so that's fine.
remove comment.

2021-11-30 14:58 UTC, martikaljuve commented on packages/reusable-transforms/src/add-missing-jsx-attribute/add-missing-jsx-attribute.ts
> +export interface ConfigToAddMissingJsxProp {
Add example as comment

2021-11-30 15:02 UTC, martikaljuve commented on packages/reusable-transforms/src/utils/getParsedImports.ts
> +          wasExportedAs?: null; // TODO `never`
apply TODO?

2021-11-30 15:04 UTC, martikaljuve commented on packages/reusable-transforms/src/utils/getParsedImports.ts
> +export const getParsedImports = <T = any>(
Maybe could add an example link to AST Explorer in a JSDoc?

2021-11-30 15:11 UTC, martikaljuve commented on packages/reusable-transforms/src/utils/getParsedImports.ts
> +            if (j.ImportDefaultSpecifier.check(specifier)) {
Would be useful to have examples as comments for the different branches here.

2021-11-30 15:13 UTC, martikaljuve commented on packages/reusable-transforms/src/utils/getParsedImports.ts
> +                /**
`import *`?

2021-12-01 13:19 UTC, martikaljuve commented on packages/reusable-transforms/src/utils/Transformer.ts
> +					...transformerParamsExceptConfig,
formatting?

2021-12-01 13:22 UTC, martikaljuve requested changes
.

2021-12-03 10:36 UTC, kiprasmel commented on packages/reusable-transforms/src/add-missing-jsx-attribute/add-missing-jsx-attribute.ts
> +export interface ConfigToAddMissingJsxProp {
added.

2021-12-03 10:46 UTC, kiprasmel commented on packages/reusable-transforms/src/utils/getParsedImports.ts
> +export const getParsedImports = <T = any>(
added.

2021-12-08 11:40 UTC, kiprasmel commented on packages/reusable-transforms/src/utils/Transformer.ts
> +					...transformerParamsExceptConfig,
prettier's fault since we didn't set up eslint. won't bother tbh.

2021-12-13 10:49 UTC, martikaljuve approved these changes

2021-12-23 00:13 UTC, merged