extraction-5-create-3rd-transform-replace-jsx-attribute
pipedrive/CodeshiftCommunity pull request #15
Opened 2021-11-30 06:14 UTC by kiprasmel

2021-11-30 14:49 UTC, martikaljuve commented on packages/reusable-transforms/src/replace-jsx-attribute/replace-jsx-attribute.spec.ts
> +    inlineTest<ConfigToModifyJSXAttributeAndItsValue>({
Maybe can try separate files like in mui-codemod? https://github.com/mui-org/material-ui/tree/master/packages/mui-codemod/src/v5.0.0

2021-12-13 11:41 UTC, kiprasmel commented on community/@pipedrive__convention-ui-react/src/misc-utils/findJsxAttribute.ts
> +        throw new Error("CODEMODS - see the above error output.");
this prolly shouldn't error, i'll add a comment instead

2021-12-13 11:49 UTC, kiprasmel commented on community/@pipedrive__convention-ui-react/src/misc-utils/findJsxAttribute.ts
> +        throw new Error("CODEMODS - see the above error output.");
done.

2021-12-13 11:57 UTC, kiprasmel commented on packages/reusable-transforms/src/replace-jsx-attribute/deletePropIfShouldBeDeleted.ts
> +            const comment: string = joinWithDeep(
refactoring this atm

2021-12-14 13:06 UTC, martikaljuve requested changes
see if you can replace inline tests with separate files.

2021-12-17 13:15 UTC, martikaljuve approved these changes

2021-12-23 00:16 UTC, merged